name: Docker Image for master branch

on: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: quay.io/cloudhut/owl-shop
          tag-semver: |
            {{raw}}
            v{{major}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: cloudhut+github_push
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
